version: '3.0'

services:
  minio:
    image: minio/minio:RELEASE.2020-04-15T19-42-18Z
    volumes:
      - ./data/minio:/data
    ports:
      - "9999:9000"
    environment:
      MINIO_ACCESS_KEY: minio # put your access key
      MINIO_SECRET_KEY: minio123 # put your secret key
    command: server /data
